#! /bin/sh
echo "Making a new BBot commit already? Wow, we are awesome!";
echo " ";
echo "[Enter your commit message below]"

read inputline
what="$inputline"

git commit -am "${what}"
bzr commit -m "${what}"

git push
bzr push
