import ConfigParser
c=ConfigParser.ConfigParser()
c.readfp(open('config','r'))
mynick=c.get('main','nick')
username=c.get('main','username')
password=c.get('main','password')
network=c.get('main','network')
port=c.getint('main','port')
autojoin=c.get('main','channels').split()
superusers=c.get('main','super-users').split()
sleep_after_join=c.getfloat('main','wait-after-identify')
wait_recv=c.getint('main','read-wait')
cmd_char=c.get('main','command-char')
error_chan=c.get('main','report-error')
allow_invite=c.get('main','allow-invite')
